config/routes.rb
Rails.application.routes.draw do
  root 'stories#new'
  resources :stories, only: %i[new create]

  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def new
  end

  def create
    client = OpenAI::Client.new(access_token: Rails.application.credentials.openai[:api_key])

    system_prompt = <<~PROMPT
      ユーザーが入力した設定で、面白おかしく展開を予想して適当な短編物語を書いて。
      文章はHTMLでフォーマットして、htmlタグやheadタグなどは無しで、h1タグとdivタグとpタグを使ってください。
    PROMPT
    user_prompt = "もしも #{params[:first_input]} が #{params[:second_input]} だったら"

    text_response = client.chat(
      parameters: {
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: system_prompt },
          { role: 'user', content: user_prompt },
        ],
        max_tokens: 2000,
      }
    )
    @story = text_response.dig('choices', 0, 'message', 'content').strip
    story_text = ActionView::Base.full_sanitizer.sanitize(@story)
    image_prompt = <<~PROMPT
      以下の設定で日本の漫画風の画像を生成してください。
      #{story_text}
    PROMPT
    image_response = client.images.generate(
      parameters: {
        prompt: image_prompt,
        model: 'dall-e-3',
        n: 1,
        size: '1024x1024',
        response_format: 'url',
      }
    )
    @image_url = image_response.dig('data', 0, 'url') || url_for('image_generate_failed.png')

    render json: { story: @story, image_url: @image_url, story_text: }
  rescue Faraday::BadRequestError => e
    render json: { error: e.message, details: e.response_body }, status: :bad_request
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 トリックオアトリート

%p あなたの友人を見つけましょう
%p あなたの友人に「トリックオアトリート！」をしてみることでナニカいいことがあるかも！

.rounded
  %table.table.table-primary
    %caption 登録しているユーザー一覧
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} First
        %th{:scope => "col"} Last
        %th{:scope => "col"} Handle
    %tbody
      %tr
        %th{:scope => "row"} 1
        %td Mark
        %td Otto
        %td @mdo
      %tr
        %th{:scope => "row"} 2
        %td Jacob
        %td Thornton
        %td @fat
      %tr
        %th{:scope => "row"} 3
        %td{:colspan => "2"} Larry the Bird
        %td @twitter

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title= content_for(:title) || 'もしもボックスジェネレータ'
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    %meta{ content: 'yes', name: 'apple-mobile-web-app-capable' }
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{ href: '/manifest.json', rel: 'manifest' }
    %link{ href: '/icon.png', rel: 'icon', type: 'image/png' }
    %link{ href: '/icon.ico', rel: 'icon', type: 'image/ico' }
    %link{ href: '/icon.png', rel: 'apple-touch-icon' }
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  %body
    = yield

app/views/stories/new.html.haml
.story-wrapper.py-3.container.d-flex.justify-content-center.align-items-center{ data: { controller: "story-generator" } }
  .text-center{ data: { story_generator_target: 'form' } }
    %h1 もしもボックスジェネレータ
    %p.text-muted あなたが想像するアニメのシチュエーションを入力してアナザーストーリーを作成してください
    = form_with url: stories_path, method: :post, remote: true, data: { action: "story-generator#submit" } do |form|
      .mb-3
        = form.label :first_input, "もしも"
        = form.text_field :first_input, class: "form-control", placeholder: "例: ドラえもん"
      .mb-3
        = form.label :second_input, "が...だったら"
        = form.text_field :second_input, class: "form-control", placeholder: "例: のび太と犬猿の仲"
      .mb-3
        = form.submit "ストーリーを生成", class: "btn btn-primary"
  .story-output.d-none{ data: { story_generator_target: 'output' } }
    = link_to '戻る', root_path, class: 'text-danger'
  .story-output-skeleton.d-none.text-center{ data: { story_generator_target: 'skeleton' } }
    %p アナザーストーリを生成中です
    %p ちょっと時間かかるよ
    %p 気長に待ってもらえると嬉しいよ
    %p ...
  .overlay.d-none.d-flex.flex-column.justify-content-center.align-items-center{"data-story-generator-target" => "overlay"}
    .spinner-border.text-primary
      %span.visually-hidden Loading...
    .loading-message.text-white{ data: { story_generator_target: "loadingMessage" } }
      %span 生成しています